- include_tasks: lookup_policy_file.yml

- name: Create a new IAM role
  iam_role:
    region: "{{ region }}"
    profile: "{{ profile|default(aws_account_name) }}"
    name: "{{ iam_role_name }}"
    path: '/'
    state: present
    assume_role_policy_document: "{{ lookup('file', 'ec2-trust-policy.json') }}"
    managed_policy: "{{ iam_managed_policies|default([]) }}"
  register: iam_result

- name: sleeping for 10 sec for the role to be available.
  pause: seconds=10
  when: iam_result.changed

- name: Create and attach instance_role_policies
  iam_policy:
    region: "{{ region }}"
    profile: "{{ profile|default(aws_account_name) }}"
    iam_type: role
    iam_name: "{{ iam_role_name }}"
    policy_name: "{{ iam_policy_name|default('minimum-ec2') }}"
    policy_json: "{{ lookup('template', '{{ iam_policy_file }}') }}"
    state: present

- name: grant iam role access to credstash key
  aws_kms:
    alias: credstash
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    description: credstash
    state: present
    grants:
      - operations:
          - Decrypt
        constraints:
          encryption_context_equals:
            Application: "{{ role_type }}"
            Environment: "{{ env }}"
        name: "{{ role_type }}-{{ env }}-encryption-context"
        grantee_principal: "{{ iam_result.iam_role.arn }}"
  when: iam_credstash_enabled|default()
